services:
  postgres:
    image: postgres:16.4-alpine
    container_name: app-db
    ports:
      - "${APP_CONFIG__DB__PORT:-5432}:5432"
    environment:
      POSTGRES_USER: "${APP_CONFIG__DB__USER:-postgres}"
      POSTGRES_PASSWORD: "${APP_CONFIG__DB__PASSWD:-postgres}"
      POSTGRES_DB: "${APP_CONFIG__DB__NAME:-postgres}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_CONFIG__DB__USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

