[project]
name = "fastapi-habbits"
version = "0.1.0"
description = ""
authors = [
    {name = "therueryan",email = "georgytoper@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings (>=2.12.0,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
